# Generated by Django 3.0.8 on 2020-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
